### ISSUE TITLE
ViaForge does not render world height correctly.

### ISSUE THREAD

**Issue by ChakaClown** [ViaVersion/ViaForge#77] opened 2023-10-26 03:18 UTC
### General Information

ViaForge (Latest version)

### Bug Description

Joining any server that is 1.19+ wont render blocks below y-level 0. When you try to go below y-level 0 you get stuck in a floating position and cannot escape.

### Steps to Reproduce

1. Set version of Minecraft to 1.19+
2. Join a server that is 1.19+
3. Go below y-level 0 to get stuck.

### Expected Behavior

Should be able to render blocks below y-level 0 in order to keep players from getting stuck.

**Comment by FlorianMichael** [comment] 2023-10-26 03:20
Duplicate of https://github.com/ViaVersion/ViaForge/issues/60

**Closed by FlorianMichael** 2023-10-26 03:20 UTC
Labels: bug
