### ISSUE TITLE
Opening whis error

### ISSUE THREAD

**Issue by DestiShell** [ViaVersion/ViaForge#144] opened 2024-12-25 15:08 UTC
### General Information

opening whis error ViaForge (viaforge) encountered an error during the common_setup event phase
Java.lang.NoClassDefFoundError: org/slf4j/spi/5LF4JServiceProvider

### Bug Description

opening whis error ViaForge (viaforge) encountered an error during the common_setup event phase
Java.lang.NoClassDefFoundError: org/slf4j/spi/5LF4JServiceProvider

### Steps to Reproduce

opening whis error ViaForge (viaforge) encountered an error during the common_setup event phase
Java.lang.NoClassDefFoundError: org/slf4j/spi/5LF4JServiceProvider

### Expected Behavior

opening whis error ViaForge (viaforge) encountered an error during the common_setup event phase
Java.lang.NoClassDefFoundError: org/slf4j/spi/5LF4JServiceProvider

**Comment by Kichura** [comment] 2024-12-25 16:32
1. Not a good issue template,
2. Duplicate of #94.

**Closed by Kichura** 2024-12-25 16:32 UTC
Labels: bug
