### ISSUE TITLE
ViaForge not working on 1.16.5

### ISSUE THREAD

**Issue by Developer-Major-Cozmic** [ViaVersion/ViaForge#135] opened 2024-11-17 03:07 UTC
### General Information

Hi, I have ViaForge 1.16.5 and I have no other mods on Forge, and when I try to load in Forge 1.16.5, 

### Bug Description

it says "ViaForge (ViaForge) encountered an error during the common_setup phase"

### Steps to Reproduce

Grab ViaForge, drop it in the Mods folder in %appdata%, load Forge 1.16.5, and boom, you get what the error says in Bug Description. 

### Expected Behavior

For the game to load properly.

**Comment by Developer-Major-Cozmic** [comment] 2024-11-17 03:08
Also, I have the crash log here:
[crash-2024-11-16_22.02.39-fml.txt](https://github.com/user-attachments/files/17788716/crash-2024-11-16_22.02.39-fml.txt)

**Comment by Developer-Major-Cozmic** [comment] 2024-11-17 03:16
I also tried Dev and the Release versions. Everything worked on 1.12.2.

**Comment by FlorianMichael** [comment] 2024-11-17 10:43
Duplicate of https://github.com/ViaVersion/ViaForge/issues/94

**Closed by FlorianMichael** 2024-11-17 10:43 UTC
Labels: bug
