### ISSUE TITLE
1.16.5 version game can't load

### ISSUE THREAD

**Issue by wasrecordrecorder** [ViaVersion/ViaForge#138] opened 2024-12-07 13:22 UTC
### General Information

ViaForge*\

### Bug Description

i'm starting forge 1.16.5 with ViaForge and getting crash
[crash-2024-12-07_16.02.05-fml.txt](https://github.com/user-attachments/files/18048489/crash-2024-12-07_16.02.05-fml.txt)

### Steps to Reproduce

Starting 1.16.5 Forge with ViaForge mod

### Expected Behavior

gane always not load

**Comment by FlorianMichael** [comment] 2024-12-07 13:50
Duplicate of https://github.com/ViaVersion/ViaForge/issues/94

**Closed by FlorianMichael** 2024-12-07 13:50 UTC
Labels: bug
